language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  skip_cleanup: true
  distributions: sdist bdist_wheel
  user: alertlogic
  password:
    secure: RtvekSNWG8UdxIHUm814PeY0vHbXXHpIDVTlrAraeNIsNMHuMIru6nvrKvOEtyTCHpvlY8dXIYPfK4M+HVm6udJFEXOAMnem1aR6IWvH3xurKfkkjMgjSnQFohzcwrmQP/x4DhE0HIZ0shE/sFAA4DzO9vjK6n5AzlbOfssdzUSkRSnVf1VfcOz3O78X/1vD4BC3hWRZ2GtKPlU8b6Hhk26tH9iQWHKU2C9XyB+V5PsSgJTGvb1tU3p29MblGNmjDyVIRNyzJhtcVTJYy8lowXR6kjqYBxd1LHr94Z/7RhS8xi3q7ii9+X4aw5Tmu0RVJumAIO8HUn7p1SHioBwidda7A0dalT2EHU3H43Geigqfox4p/U5UvqgjiUt7151TJ05rPxogGUDhhb5SnIRlF937mUNNkKh7cMtevPDtT3r1boZ+aXXo9bIjA4KDD9STrZoz/smQ7QCx1p+nMYEjIVV0F+nwUlpGSTG5swpoz7ZNhDfJ4u+7da/GpoUKtV33sFGliCGIzPBMxKxy8/ArwJwceZdj97CinX0uMbPBW/m80ViTSh2Ko7DPWyi27q8esnt7p+tAHAnZ74nm2fbew1GEDo4ArYzzGG6IcyceGRLbQ7OTg6hs0w+otx597pxE5VxReKaWjfek4UrrZU3nJM8dlUIJNZ0sL7ThLDMhjmk=
  on:
    tags: true
    repo: anton-b/alertlogic-sdk-python
    python: 3.8
