language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  server: https://test.pypi.org/
  distributions: sdist bdist_wheel
  user: alertlogic
  password:
    secure: YHhH3WkfqAKCtkrA2XOHbPXxqN61uCHYNcHOJRLTo8XtHcrrsLAOynr0KmYYj6QghJe/ZGrYHOfhojEt88lBsvPC2KAhxKm3vTQgG0EayUpJoc12Q5eGHwcX0IPUNbIPdaFSxjJF315saHzvgbc0KKvWLOA6Z/UbLyyn7MNQFQUgC/Hiy2TBnXLAUV6m5ZMrLL3/0wqN+U3cgUAb32PTicmQGGf1x/BFs5wCgSyrg4tq66kcqEK+412H8HhuLXGrUe3ba9wDR2UX0FaLgnssG906Wl0M6H62Q1G3Nm1DCY20LGzR/ipqxQHhN8S7z3V6jfgYhtjNRjt47VHGLTUxS/Fh4u1d3JbExoU5ryHf5NcYEkt/a8Oe1L1No/f+GFy8r0ulvzlssYoLEHFmkyCur/CQP+ExKKiZ5Gatz3rVV5cv91z4MTxfTlOaxKO7IvTA47WWrtE80iQcvFNwzz5Dzc+86ohAIK42rcuZPwNlxENOKovmdaqGSSyjUmqmSVGuOm9596p7TcHGH3ZuXGY1kQJF/t0xbqlXIz8NJqkUrMocxF+qAOPku1ncV0P2ccwG7xlwuOCGGhixA9rgDSzh/FLRhBHCFotP6fSDAIPuNv+qNPqrPqvDPJz6eCv5vf3ZaiTD9ZtTRvPghtGYGSCItpaUS6MWNoOOrvSWH6rItbw=
  on:
    tags: true
    repo: anton-b/alertlogic-sdk-python
    python: 3.8
