language: python
python:
- 3.8
- 3.7
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  server: https://test.pypi.org/legacy/
  skip_cleanup: true
  distributions: sdist bdist_wheel
  user: "__token__"
  password:
    secure: "esg0/9nZt3bF7XFmOHVJsrIIXWcLVcZFja7Ucm60TfVK5vCEhjdLN/wQ1PTouLz47JVbBCJulYi2en8X9mw4/krDhEkVSEWGsg658CGj4Vw4CKzHux9VKiL78dSpNjkOhMmujzg1V7I6kCnTfhmV/flxdV3G5Mil8eAv0Xivkj6+Goz0oG3zvmWHtY58TGf6/nhC7MYwO8ccLUjLgbtWPL+0iRsrPjCjwdJgIF9NYGP2t3XEqRiu3RoGf7DccXhKmXifCmEMwJEiCjRBqRjmq+QClxwLZvTwI4YnG5Q9XpE5NvGRmKz6mj7s7PIuj5Au1YwHxSgo9/Uc6j+pYH4cgGwBTTVK/4iKBxiYR4oa8pHDcTmY/iJ3Uw+UuOcCL3TV9dCLGeerWElgSiSX5iIXv+JUBjRbVWtxYlB51gTNC9/nh1mwsap3VxCSOui/xEZ3FuR7f6S1AonRcGgShWi+70lSE2FyxiD4GmlwXaA8f5Bl+4LxNXLAS0BU2LKhFXbq9+GpGW8BoiwakreTMepyEYlEUxW9ceK3LDV26UYUVtn01v3IOfzsOTQqJ4l9DOmWqouNJzNApk3YfHu715MSu7VCGL0B9mTVLLyzldBVtjYO5/RU40Mh/9cusFqid4RPx6923SG2jnRlub9f1+/FCNltyCViKY5hraQnWw2SzGM="
  on:
    tags: true
    repo: anton-b/alertlogic-sdk-python
    python: 3.8
